# -*- coding: utf-8 -*-
"""BASE_1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1xbawLXUReBhp1JIQ6-_OgHZWlTlSWoV1

ruta db



```
# Tiene formato de código
/content/drive/MyDrive/Colab_Notebooks/BASEDEDATOS1/BASE_1.csv
```
"""

import pandas as pd
datos=pd.read_csv("/content/drive/MyDrive/Colab_Notebooks/BASEDEDATOS1/db_load.csv")
datos

import pandas as pd
datos=pd.read_csv("/content/drive/MyDrive/Colab_Notebooks/BASEDEDATOS1/db_load.csv")
#print(datos)
datos.drop(["Hyperlink to Ordinance"], axis=1, inplace=True)
datos.drop(["Ordinance"], axis=1, inplace=True)
datos
df_filtered = datos[datos["Product Type"] != "Straw"]
df_filtered

"""Lo que hicimos fue elminar la columna de los hipervínculos, que no nos interesaba en nuestra investigación. También filtramos todo lo que no eran bolsas en la columna del tipo de producto. Además, eliminamos la columna de ordinance.

"""

df_filtered.to_csv("df_filtered.csv", header=True, index=False)
df_filtered