# -*- coding: utf-8 -*-
"""GallegoEntrega_02

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ybIcpwP8Jlq-q-CUdlzDMglk_Ui42xnJ

Base de datos: Reciclaje de plastico en Regiones
"""

import pandas as pd
import seaborn as sns

r_bolsas = pd.read_excel ("/content/drive/MyDrive/Reciclaje de envases plásticos por región.xlsx")

r_bolsas.head ()

columnas_a_eliminar = ("Centros de acopio (Ton/mes)")

r_bolsas = r_bolsas.drop(columnas_a_eliminar, axis=1)

print("\nr_bolsas después de eliminar las columnas:")
print(r_bolsas)